### ISSUE TITLE
Nickname Gets Truncated

### ISSUE THREAD

**Issue by axetota** [SlitherSessions/ss-mods#4]
If one uses a nickname that is to long, then it is truncated.

**Comment by axetota** [comment]
turns out this is a limitation of slither.io itself.  For example if you use the nickname [SS] Just Keep Slithering, the last 'g' is truncated with or without the mods turned on. closing.

**Comment by timurtripp** [comment]
Issue can now be considered closed, as a space will no longer be added after the clan tag if the nickname is 20 characters ([SS]Just Keep Slithering instead of [SS] Just Keep Slithering, the latter gets the 'g' truncated).
